/* eslint-disable */
/* global WebImporter */

/**
 * Transformer: WKND site-wide cleanup.
 *
 * Removes non-authorable site chrome so the imported document contains only
 * page-level authored content. Every selector below was verified against the
 * captured DOM in migration-work/templates/{home,magazine-landing,
 * magazine-article,about}/cleaned.html (WKND / AEM core components).
 *
 * Notes on what is intentionally NOT here:
 *  - No cookie/consent/OneTrust/Cybot selectors: none of the four captured
 *    templates contain any cookie or consent widget markup.
 *  - No ContextHub / cq-* / granite editor artifacts: the captured pages are
 *    published (anonymous) output and contain no author-layer/editor markup
 *    (the only "granite" hit in the source is body copy: "granite cliffs").
 *  Both are documented here rather than guessed at with invented selectors.
 */

const TransformHook = {
  beforeTransform: 'beforeTransform',
  afterTransform: 'afterTransform',
};

export default function transform(hookName, element, payload) {
  if (hookName === TransformHook.beforeTransform) {
    // Interactive / overlay chrome that sits as siblings of the content and
    // could interfere with block parsing. Verified in cleaned.html:
    //   #toggleNav        -> mobile hamburger toggle (home line 568)
    //   #mobileNav        -> mobile off-canvas navigation (home line 574)
    //   iframe#destination_publishing_iframe_wkndsite_0 -> Adobe demdex
    //                        ID-syncing iframe (home line 566)
    WebImporter.DOMUtils.remove(element, [
      '#toggleNav',
      '#mobileNav',
      '#destination_publishing_iframe_wkndsite_0',
    ]);

    // Adventures landing: the "Current Adventures" grid is an AEM tabs component
    // with an active "All" panel (16 cards) plus 6 category-subset panels that
    // DUPLICATE those cards, and a tablist of category buttons. The
    // adventure-list block is mapped to the active panel; the inactive panels +
    // tablist would otherwise leak in as duplicate default content. Remove them
    // BEFORE parsing so only the active panel (consumed by the block) remains.
    // Verified in adventures-landing/cleaned.html: 7 .cmp-tabs__tabpanel (1
    // --active), 1 .cmp-tabs__tablist. No-op on templates without tabs.
    element.querySelectorAll('.cmp-tabs__tabpanel:not(.cmp-tabs__tabpanel--active)').forEach((el) => el.remove());
    WebImporter.DOMUtils.remove(element, [
      '.cmp-tabs__tablist',
    ]);
  }

  if (hookName === TransformHook.afterTransform) {
    // 1) Shared experience-fragment header & footer. Migrated separately as
    //    the EDS nav/footer blocks, so they must be stripped from page content.
    //    Verified: header.experiencefragment.cmp-experiencefragment--header
    //    (home line 5), footer.experiencefragment.cmp-experiencefragment--footer
    //    (home line 471). Present on all four templates.
    WebImporter.DOMUtils.remove(element, [
      'header.cmp-experiencefragment--header',
      'footer.cmp-experiencefragment--footer',
    ]);

    // 2) Header-embedded utility widgets. These live inside the header XF above
    //    (so already removed with it), but are targeted explicitly for
    //    robustness in case a template variant surfaces them outside the header.
    //    Verified in cleaned.html:
    //      .sign-in-buttons                 (home line 14)
    //      .languagenavigation              (home line 21)
    //      .cmp-search--header / .cmp-search (home lines 134-135)
    WebImporter.DOMUtils.remove(element, [
      '.sign-in-buttons',
      '.languagenavigation',
      '.search.cmp-search--header',
    ]);

    // 3) Breadcrumb navigation. Present on the magazine-article template only
    //    (magazine-article line 170: div.breadcrumb / .cmp-breadcrumb). In EDS
    //    this is auto-generated by the template, not authored per page.
    WebImporter.DOMUtils.remove(element, [
      '.breadcrumb',
      '.cmp-breadcrumb',
    ]);

    // 4) Generic non-authorable elements and stray markup artifacts.
    //    <meta> tags appear inline inside cmp-image blocks (e.g. home line 183);
    //    script/style/noscript/link/iframe are removed defensively (standard,
    //    safe tag-level removals; the demdex iframe is already gone above).
    WebImporter.DOMUtils.remove(element, [
      'script',
      'style',
      'noscript',
      'link',
      'iframe',
      'meta',
    ]);

    // 5) Strip non-authorable AEM data-layer / accessibility tracking attributes
    //    seen on <body> and components (e.g. home line 1). These are runtime
    //    concerns, not authored content.
    element.querySelectorAll('[data-cmp-data-layer], [data-cmp-data-layer-enabled], [data-cmp-data-layer-name], [data-cmp-link-accessibility-enabled], [data-cmp-link-accessibility-text]').forEach((el) => {
      el.removeAttribute('data-cmp-data-layer');
      el.removeAttribute('data-cmp-data-layer-enabled');
      el.removeAttribute('data-cmp-data-layer-name');
      el.removeAttribute('data-cmp-link-accessibility-enabled');
      el.removeAttribute('data-cmp-link-accessibility-text');
    });

    // 6) Rewrite internal WKND links to the clean EDS paths so authored links
    //    (featured "Read More", home teasers/CTAs) point at the migrated pages
    //    rather than the old /us/en/*.html source URLs. Mirrors the path map in
    //    the import scripts' toEdsPath():
    //      /us/en(.html)             -> /
    //      /us/en/about-us(.html)    -> /about
    //      /us/en/magazine(.html)    -> /magazine
    //      /us/en/magazine/<slug>    -> /magazine/<slug>
    //    Non-migrated sections (adventures, faqs) keep an absolute link to the
    //    live source so they don't 404 within the migrated site.
    element.querySelectorAll('a[href]').forEach((a) => {
      const raw = a.getAttribute('href');
      if (!raw) return;
      // Normalise: work on the path portion of same-site links only.
      let path = raw;
      try {
        if (/^https?:\/\//i.test(raw)) {
          const u = new URL(raw);
          if (!/wknd\.site$/i.test(u.hostname)) return; // external link, leave as-is
          path = u.pathname + u.search + u.hash;
        }
      } catch (e) {
        return;
      }
      if (!path.startsWith('/us/en')) return; // not a localized WKND path

      const clean = path.replace(/\.html?(?=$|[?#])/, '');
      if (/^\/us\/en(\/)?(?=$|[?#])/.test(clean)) {
        a.setAttribute('href', clean.replace(/^\/us\/en\/?/, '/'));
      } else if (/^\/us\/en\/about-us(?=$|[?#])/.test(clean)) {
        a.setAttribute('href', clean.replace('/us/en/about-us', '/about'));
      } else if (/^\/us\/en\/magazine(\/|$|[?#])/.test(clean)) {
        a.setAttribute('href', clean.replace('/us/en/magazine', '/magazine'));
      } else if (/^\/us\/en\/(adventures|faqs)(\/|$|[?#])/.test(clean)) {
        // Not in migration scope — point at the live source to avoid 404s.
        a.setAttribute('href', `https://wknd.site${path}`);
      } else {
        // Any other localized path: strip the /us/en prefix.
        a.setAttribute('href', clean.replace(/^\/us\/en/, '') || '/');
      }
    });

    // 7) Accessibility: fill empty/missing alt text on content images. WKND
    //    source images frequently ship with alt="". Derive a human-readable
    //    label from the image filename (e.g. "surfer-back-from-the-ocean.jpeg"
    //    -> "Surfer back from the ocean") so every content image conveys
    //    meaning for screen readers and passes accessibility audits.
    element.querySelectorAll('img').forEach((img) => {
      const alt = img.getAttribute('alt');
      if (alt && alt.trim()) return; // already has meaningful alt
      const src = img.getAttribute('src') || '';
      const file = src.split('/').pop() || '';
      const base = file
        .replace(/\.[a-z0-9]+$/i, '') // drop extension
        .replace(/\.coreimg.*$/i, '') // drop AEM rendition suffix if present
        .replace(/[-_]+/g, ' ') // separators -> spaces
        .replace(/\b\d{6,}\b/g, '') // drop long numeric IDs
        .replace(/\s+/g, ' ')
        .trim();
      if (base) {
        img.setAttribute('alt', base.charAt(0).toUpperCase() + base.slice(1));
      } else {
        // Purely decorative (no usable filename): mark explicitly decorative.
        img.setAttribute('alt', '');
        img.setAttribute('role', 'presentation');
      }
    });
  }
}
